config/routes.rb
Rails.application.routes.draw do
  get 'welcome/lunch_menu'

  root  'welcome#index'

end

app/models/lunch_menu_config.rb
require 'yaml'
class LunchMenuConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/pizza_calzone_pasta.yml"))
    end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/menu_config.rb
require 'yaml'
class MenuConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/config.yml"))
    end
end

app/models/pizza_lunch_config.rb
require 'yaml'
class PizzaLunchConfig
    def self.current_menu
        current_menu = load_menu
    end
    def self.load_menu
         YAML.load(File.read("#{Rails.root.to_s}/config/pizza_lunch.yml"))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @menu_items = Menu.all
  end
  
  def lunch_menu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
             <%= link_to "lunch menu", welcome_lunch_menu_path %>
            <form id='form' >
                <div class="box">
                  <% MenuConfig.current_menu.each do |item,content| %> 
                    <div class="top">
                        <h5><%= item%></h5>
                    </div>
                    <div class="bottom">
                      <% content.each do |subject,detail| %>
                       <input type="checkbox" name="menItems"  onclick="myFunction(this)" 
                value="<%= subject["name"] %>&nbsp;&nbsp;&nbsp;&nbsp;<%= subject["price"] %>">
                            <%= subject["name"] %><br>
                            <% unless subject["ingredients"].nil?  %>
                                <%= subject["ingredients"]%>
                                <%= tag(:br) %>
                            <%end%>
                            <%= subject["price"] %><br>
                       <%end%>
                    </div>
                     <%end%>
                </div>
            </form>
        <!--<div id = "ordered-list" class="col-md-6">-->
        <!--    <h1>Ordered List</h1>-->
        <!--    <div id="order">-->
        <!--    </div>-->
        <!--</div> -->
      </div>
     
    </div>
    
</div>
</div>

app/views/welcome/lunch_menu.html.erb
<h1>Lunch Menu </h1>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6">
            <form id='form' >
                <div class="box" style="margin-top: 22px;">
                  <% LunchMenuConfig.current_menu.each do |item,content| %> 
                    <div class="top">
                        <span>
                            <%= item%> 
                            <span style="color: lightgray;float:right;">v</span>
                        </span>
                    </div>
                    <div class="bottom">
                      <% content.each do |subject,detail| %>
                       <input type="checkbox" name="menItems"  onclick="myFunction(this)" 
                value="<%= subject["name"] %>&nbsp;&nbsp;&nbsp;&nbsp;<%= subject["price"] %>">
                            <%= subject["name"] %><br>
                            <% unless subject["ingredients"].nil?  %>
                                <%= subject["ingredients"]%>
                                <%= tag(:br) %>
                            <%end%>
                            <%= subject["price"] %><br>
                       <%end%>
                    </div>
                     <%end%>
                </div>
            </form>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <h1 class="text-center"   style="color:red;"> PIZZA</h1>
            <div class ="text-center" style="border: 1px solid red; color: #fff; background: red;">
                <h2>BUY 1 GET 1 FREE </h2>
            </div>
            <div class="top">
                <h2 style="color: green; margin-top: 25px; padding: 25px;border: 1px solid red; background:red;">TOPPINGS: 
                 <span style="color: lightgray;float:right;">v</span>
                </h2>
            </div>
            <div class="bottom" style="display:none;">
                <p  style="color: red; font-weight: 700"  >
                    Pepperoni, Italian Sausage, Chicken, Mushrooms, Onions, Bell Peppers, 
                    Candian Bacon, Black Olives, Meatballs, Ham, Pineapple, Jalapenos,
                    Salami, Anchovies, Fresh Tomatoes, Fresh Garlic, Roasted Garlic, 
                    Cilantro, Grilled Eggplant, Grilled Zucchini, Red Onion, Roasted Peppers
                    , Capers, Sun-dried Tomatoes, Feta Cheese, Artichoke Hearts
                </p>
            </div>
            
             <div style="text-align: right; color:green; font-weight: 500;margin-bottom: 19px;">
               SMALL(2)&nbsp;&nbsp;MEDIUM(2)&nbsp;&nbsp;LARGE(2)
            </div>
            <div class="box" id="topping-pizza">
                  <% PizzaLunchConfig.current_menu.each do |item,content| %> 
                      <% content.each do |subject,detail| %>
                        <div  class="top" style="text-align: left;">
                            <span style=" display: inline-block;">
                                <%= subject["name"] %>
                            </span>
                            <span style="float:right; color: red;">
                                <% subject["price"].each do |p| %>
                                    <%= p %>&nbsp;&nbsp; 
                                <%end%>  
                                <span style="color: lightgray;text-align:right;">v</span>
                            </span> 
                            <span>
                            <%= tag(:br) %>
                            </span>
                         </div>   
                         <% unless subject["ingredients"].nil?  %>
                             <div class="bottom">
                                <%= subject["ingredients"]%>
                             </div>
                         <%end%>
                       <%end%>
                 <%end%>
             </div>
        </div>
        
        
    </div>
       <div class="row ">
           <div class="col-md-12 text-center">
               <h2 style="margin-top:25px;">CICCERO'S TREAT</h2>
           </div>
           <div class="dashed-red">
               <div class="col-md-4" style="float:right;" >
                 <h5>2 Large Pizzas with 3 Toppings and 3 Cans of Soda <span style="color:red">(excluding Extra Cheese)</span></h5> 
                 <h6>for only 
                       <span style="color:red">
                           $23.50 + tax
                       </span>
                   </h6>
                </div>
                <div class="col-md-4" style="float:right;">
                   <h5>Large Pizza <span style="color:red">(one only)</span> with 3 Toppings, Large Green Salad & 3 Cans of Soda </h5>
                   <h6>for only 
                       <span style="color:red">
                           $23.50 + tax
                       </span>
                   </h6>
                </div>
                <div class="col-md-4" style="float:right;" >
                   <h5>1 Small Pizza with 2 Toppings, 1 Pasta of Your Choice, 2 Dinner Salads & 2 Cans of Soda</h5>
                   <h6>for only 
                       <span style="color:red">
                           $19.50 + tax
                       </span>
                   </h6>
                </div>
           </div>
       </div>
    </div>
      <!--  <div class="row">-->
      <!--  <div id = "ordered-list" class="col-md-6">-->
      <!--      <h1>Ordered List</h1>-->
      <!--      <div id="order">-->
      <!--      </div>-->
      <!--  </div> -->
      <!--</div>-->
     
    </div>
    
</div>
</div>